Repository ultraleap/UnityPlugin, pull requests merged in 2018-05, with the labels that each got.

#1025 Can (un)ignore IE checks, LM window on play if fail
  Assets/LeapMotion/Core/Scripts/EditorTools/LeapProjectChecks.cs
  Assets/LeapMotion/Modules/InteractionEngine/Scripts/Internal/Editor/InteractionChecks.cs
Labels: DevX

#1029 Updtaed VRvisualizer graphics to match internal visualizer more closely
  Assets/LeapMotion/Core/Scripts/Hands/CapsuleHand.cs
  Assets/LeapMotion/Internal/VRVisualizer/ScenesResources/CapsuleHandMat.mat
  Assets/LeapMotion/Internal/VRVisualizer/ScenesResources/CapsuleHandMat.mat.meta
  Assets/LeapMotion/Internal/VRVisualizer/VRVisualizer.unity
Labels: enhancement

#1030 Remove erroneous smoothed tracking latency
  Assets/LeapMotion/Core/Scripts/LeapXRServiceProvider.cs
Labels: bug

#1031 Moved file into the graphic renderer namespace
  Assets/LeapMotion/Modules/GraphicRenderer/Scripts/Editor/LeapGraphicEditor.cs
Labels: bug

#1033 Fixes and some improvements to QuickButton
  Assets/LeapMotion/Core/Scripts/Attributes/QuickButton.cs
Labels: bug, enhancement

#1032 Add attempts to reconnect to the service when not connected
  Assets/LeapMotion/Core/Scripts/LeapServiceProvider.cs
Labels: bug

#1034 Fix gr gamma linear tint
  Assets/LeapMotion/Modules/GraphicRenderer/Scripts/RenderingMethods/LeapMesherBase.cs
Labels: Graphic Renderer, bug

#1035 Fix the Shadows in the Infrared Passthrough Scenes
  Assets/LeapMotion/Core/Examples/Capsule Hand (VR - Infrared Viewer).unity
  Assets/LeapMotion/Core/Examples/Rigged Hands (VR - Infrared Viewer).unity
  Assets/LeapMotion/Core/Scripts/Hands/CapsuleHand.cs
  Assets/LeapMotion/Internal/VRVisualizer/VRVisualizer.unity
Labels: bug

#1036 Switch the Reconnection Counter to use frame number
  Assets/LeapMotion/Core/Scripts/LeapServiceProvider.cs
Labels: bug

#1037 Fixed tinting for text renderers too
  Assets/LeapMotion/Modules/GraphicRenderer/Scripts/RenderingMethods/LeapTextRenderer.cs
Labels: Graphic Renderer, bug

#1039 Fix visualizer policy and images
  Assets/LeapMotion/Core/Plugins/LeapCSharp/Connection.cs
  Assets/LeapMotion/Internal/VRVisualizer/ScenesResources/Scripts/VisualizerManager.cs
  ProjectSettings/ProjectSettings.asset
Labels: DevX, enhancement
