Repository ultraleap/UnityPlugin, pull requests merged in 2018-02, with the labels that each got.

#951 Merge a number of utilities from the Paint project
  Assets/LeapMotion/Core/Scripts/Attributes/AutoFind.cs
  Assets/LeapMotion/Core/Scripts/Attributes/AutoFind.cs.meta
  Assets/LeapMotion/Core/Scripts/Attributes/ImplementsTypeNameDropdown.cs
  Assets/LeapMotion/Core/Scripts/Attributes/ImplementsTypeNameDropdown.cs.meta
  Assets/LeapMotion/Core/Scripts/Attributes/QuickButton.cs
  Assets/LeapMotion/Core/Scripts/Attributes/QuickButton.cs.meta
  Assets/LeapMotion/Core/Scripts/Attributes/RunTimeOnly.cs
  Assets/LeapMotion/Core/Scripts/Attributes/RunTimeOnly.cs.meta
  Assets/LeapMotion/Core/Scripts/Attributes/Units.cs
  Assets/LeapMotion/Core/Scripts/Attributes/Units.cs.meta
  Assets/LeapMotion/Core/Scripts/DataStructures/DelayBuffer.cs
  Assets/LeapMotion/Core/Scripts/DataStructures/DeltaBuffer.cs
  Assets/LeapMotion/Core/Scripts/DataStructures/IIndexable.cs
  Assets/LeapMotion/Core/Scripts/DataStructures/IIndexable.cs.meta
  Assets/LeapMotion/Core/Scripts/DataStructures/IIndexableStruct.cs
  Assets/LeapMotion/Core/Scripts/DataStructures/IIndexableStruct.cs.meta
  Assets/LeapMotion/Core/Scripts/DataStructures/Pool.cs
  Assets/LeapMotion/Core/Scripts/DataStructures/ReadonlySlice.cs
  Assets/LeapMotion/Core/Scripts/DataStructures/ReadonlySlice.cs.meta
  Assets/LeapMotion/Core/Scripts/DataStructures/RingBuffer.cs
  Assets/LeapMotion/Core/Scripts/DataStructures/Slice.cs
  Assets/LeapMotion/Core/Scripts/DataStructures/Slice.cs.meta
  Assets/LeapMotion/Core/Scripts/Utils/HandUtils.cs
  Assets/LeapMotion/Core/Scripts/Utils/Infix.cs
  Assets/LeapMotion/Core/Scripts/Utils/Infix.cs.meta
  Assets/LeapMotion/Core/Scripts/Utils/LeapColor.cs
  Assets/LeapMotion/Core/Scripts/Utils/LeapColor.cs.meta
  Assets/LeapMotion/Core/Scripts/Utils/TransformHistory.cs
  Assets/LeapMotion/Core/Scripts/Utils/Utils.cs
Labels: enhancement

#950 Fixed failing template tests
  Assets/LeapMotion/Core/Scripts/Utils/Editor/BitConverterNonAllocTests.cs
  Assets/LeapMotion/Generation/BitConverter/BitConverterGenerator.cs
  Assets/LeapMotion/Generation/BitConverter/Editor/BitConverterTestsTemplate.cs
  Assets/LeapMotion/Generation/Editor/GeneratorEditor.cs
Labels: bug, enhancement

#955 Remove pooling extensions for the indexable struct wrapper
  Assets/LeapMotion/Core/Scripts/DataStructures/IIndexableStruct.cs
Labels: DevX, bug

#956 Fixed handmodelbase provider hand logic
  Assets/LeapMotion/Core/Scripts/Hands/HandModelBase.cs
Labels: bug

#960 Null check in handmodelbase for the frame
  Assets/LeapMotion/Core/Scripts/Hands/HandModelBase.cs
Labels: bug
