Repository ultraleap/UnityPlugin, pull requests merged in 2018-03, with the labels that each got.

#966 Fix dictionary and hashset serializing
  Assets/LeapMotion/Core/Scripts/DataStructures/Editor/SerializableDictionaryEditor.cs
  Assets/LeapMotion/Core/Scripts/DataStructures/Editor/SerializableHashSetEditor.cs
  Assets/LeapMotion/Core/Scripts/DataStructures/ReadonlyHashSet.cs
  Assets/LeapMotion/Core/Scripts/DataStructures/SerializableDictionary.cs
  Assets/LeapMotion/Core/Scripts/DataStructures/SerializableHashSet.cs
  Assets/LeapMotion/Modules/InteractionEngine/Scripts/UI/Anchors/AnchorGroup.cs
Labels: bug, enhancement

#961 Tune Grab and Soft-Contact; add support back to 5.6
  Assets/LeapMotion/Core/Scripts/LeapXRServiceProvider.cs
  Assets/LeapMotion/Core/Scripts/Utils/Infix.cs
  Assets/LeapMotion/Core/Scripts/Utils/Utils.cs
  Assets/LeapMotion/Core/Scripts/Utils/XRSupportUtil.cs
  Assets/LeapMotion/Core/Scripts/XR/Editor/XRHeightOffsetEditor.cs
  Assets/LeapMotion/Core/Scripts/XR/XRHeightOffset.cs
  Assets/LeapMotion/Experimental/HierarchyRecording/Scripts/HierarchyRecorder.cs
  Assets/LeapMotion/Internal/RealtimeGraph/Scripts/RealtimeGraph.cs
  Assets/LeapMotion/Modules/InteractionEngine/Plugins/InteractionEngineUtility.dll
  Assets/LeapMotion/Modules/InteractionEngine/Scripts/InteractionController.cs
  Assets/LeapMotion/Modules/InteractionEngine/Scripts/InteractionHand.cs
  Assets/LeapMotion/Modules/InteractionEngine/Scripts/InteractionManager.cs
  Assets/LeapMotion/Modules/InteractionEngine/Scripts/InteractionXRController.cs
  Assets/LeapMotion/Modules/InteractionEngine/Scripts/Internal/DefaultXRNodeTrackingProvider.cs
  Assets/LeapMotion/Modules/InteractionEngine/Scripts/Internal/HeuristicGrabClassifier.cs
Labels: Interaction Engine, bug, enhancement

#949 Added null check to HandPool
  Assets/LeapMotion/Core/Scripts/HandModelManager.cs
Labels: bug

#973 Procedural graphics reuse meshes, dynamic renderer clears cache
  Assets/LeapMotion/Modules/GraphicRenderer/Scripts/Graphics/ProceduralMeshGraphics/LeapBoxGraphic.cs
  Assets/LeapMotion/Modules/GraphicRenderer/Scripts/Graphics/ProceduralMeshGraphics/LeapPanelGraphic.cs
  Assets/LeapMotion/Modules/GraphicRenderer/Scripts/Graphics/ProceduralMeshGraphics/LeapPanelOutlineGraphic.cs
  Assets/LeapMotion/Modules/GraphicRenderer/Scripts/Graphics/ProceduralMeshGraphics/LeapSpriteGraphic.cs
  Assets/LeapMotion/Modules/GraphicRenderer/Scripts/RenderingMethods/LeapDynamicRenderer.cs
Labels: bug

#975 Fix property height in CombinablePropertyDrawer
  Assets/LeapMotion/Core/Scripts/Attributes/Editor/CombinablePropertyDrawer.cs
Labels: bug

#959 Added FindAllAssetsOfType to fix weird bug
  Assets/LeapMotion/Core/Scripts/Utils/EditorResources.cs
  Assets/LeapMotion/Internal/Generation/Editor/GeneratorEditor.cs
  Assets/LeapMotion/Internal/Package/BuildDefinition.cs
  Assets/LeapMotion/Internal/Package/PackageDefinition.cs
  Assets/LeapMotion/Internal/RealtimeGraph/Package.asset
  Assets/LeapMotion/Legacy/Attachments/Package.asset
  Assets/LeapMotion/Legacy/DetectionExamples/Package.asset
  Assets/LeapMotion/Legacy/UIInput/Package.asset
Labels: bug

#967 Merge Paint Things 2 (electric boogaloo)
  .gitignore
  Assets/LeapMotion/Core/Scripts/Attachments/AttachmentPointBehaviour.cs
  Assets/LeapMotion/Core/Scripts/Attributes/CombinablePropertyAttribute.cs
  Assets/LeapMotion/Core/Scripts/Attributes/Editor/CombinablePropertyDrawer.cs
  Assets/LeapMotion/Core/Scripts/Attributes/ImplementsInterface.cs
  Assets/LeapMotion/Core/Scripts/Attributes/OnEditorChange.cs
  Assets/LeapMotion/Core/Scripts/DataStructures/Maybe.cs
  Assets/LeapMotion/Core/Scripts/DataStructures/ReadonlyList.cs
  Assets/LeapMotion/Core/Scripts/Utils/RuntimeColliderGizmos.cs
  Assets/LeapMotion/Core/Scripts/Utils/RuntimeGizmoManager.cs
  Assets/LeapMotion/Core/Scripts/Utils/Utils.cs
  Assets/LeapMotion/Modules/InteractionEngine/Scripts/InteractionBehaviour.cs
  Assets/LeapMotion/Modules/InteractionEngine/Scripts/InteractionController.cs
  Assets/LeapMotion/Modules/InteractionEngine/Scripts/InteractionManager.cs
  Assets/LeapMotion/Modules/InteractionEngine/Scripts/UI/InteractionSlider.cs
  Assets/LeapMotion/Modules/InteractionEngine/Scripts/UI/InteractionToggle.cs
Labels: Interaction Engine, enhancement

#974 Fix playmode tests
  Assets/LeapMotion/Modules/GraphicRenderer/Testing/Scripts/Tests/TestActualShaderOutput.cs
  Assets/LeapMotion/Modules/InteractionEngine/Testing/EditorResources/IE Test Default Rig.prefab
  Assets/LeapMotion/Modules/InteractionEngine/Testing/EditorResources/IE Test Playback Rig - Grasp and Throw.prefab
  Assets/LeapMotion/Modules/InteractionEngine/Testing/EditorResources/IE Test Playback Rig - Press Button.prefab
  Assets/LeapMotion/Modules/InteractionEngine/Testing/Scripts/InteractionEngineTestBase.cs
  Assets/LeapMotion/Modules/InteractionEngine/Testing/Scripts/Tests/CreationAndDeletionTests.cs
  Assets/LeapMotion/Modules/InteractionEngine/Testing/Scripts/Tests/InteractionButtonTests.cs
Labels: bug

#982 Overhaul query testing and fixed some bugs!
  Assets/LeapMotion/Core/Scripts/Query/Editor/QueryTests.cs
  Assets/LeapMotion/Core/Scripts/Query/QueryOperatorExtensions.cs
Labels: bug, enhancement
