Repository ultraleap/UnityPlugin, pull requests merged in 2018-04, with the labels that each got.

#985 Query tweaks
  Assets/LeapMotion/Core/Scripts/Query/Editor/QueryTests.cs
  Assets/LeapMotion/Core/Scripts/Query/QueryCollapseExtensions.cs
  Assets/LeapMotion/Core/Scripts/Query/QueryOperatorExtensions.cs
Labels: enhancement

#988 Incremental Additions, 2018-04-02
  Assets/LeapMotion/Core/Scripts/Utils/AnimationCurveUtil.cs
  Assets/LeapMotion/Modules/InteractionEngine/Scripts/InteractionBehaviour.cs
  Assets/LeapMotion/Modules/InteractionEngine/Scripts/Internal/RigidbodyWarper.cs
  Assets/LeapMotion/Modules/InteractionEngine/Scripts/Utility/Editor/IgnoreColliderForInteractionEditor.cs
  Assets/LeapMotion/Modules/InteractionEngine/Scripts/Utility/Editor/IgnoreColliderForInteractionEditor.cs.meta
  Assets/LeapMotion/Modules/InteractionEngine/Scripts/Utility/IgnoreColliderForInteraction.cs
  Assets/LeapMotion/Modules/InteractionEngine/Scripts/Utility/IgnoreColliderForInteraction.cs.meta
  ProjectSettings/ProjectSettings.asset
Labels: Interaction Engine, enhancement

#997 Tweaked worker thread profiling text
  Assets/LeapMotion/Core/Editor/LeapServiceProviderEditor.cs
  Assets/LeapMotion/Core/Scripts/LeapServiceProvider.cs
Labels: DevX

#998 Delete annoying "No LeapProvider" warning
  Assets/LeapMotion/Core/Scripts/Utils/HandUtils.cs
Labels: DevX

#1001 Fixed units of TimeVisible
  Assets/LeapMotion/Core/Plugins/LeapCSharp/CopyFromLeapCExtensions.cs
Labels: bug

#994 Fix null reference b/c _softContactsToDraw wasn't initialized
  Assets/LeapMotion/Core/Scripts/Hands/HandModelBase.cs
  Assets/LeapMotion/Modules/InteractionEngine/Scripts/InteractionManager.cs
Labels: bug

#995 Add ScaleLastFingerBones option to RiggedHand, enabled by default
  Assets/LeapMotion/Core/Examples/Rigged Hands (VR).unity
  Assets/LeapMotion/Core/Scripts/Hands/RiggedFinger.cs
  Assets/LeapMotion/Core/Scripts/Hands/RiggedHand.cs
Labels: Hands Module, bug

#989 Introduce the "Post-Process Provider" Pattern
  Assets/LeapMotion/Core/Examples/Example Assets/InertiaPostProcessingProvider.cs
  Assets/LeapMotion/Core/Examples/Example Assets/InertiaPostProcessingProvider.cs.meta
  Assets/LeapMotion/Core/Examples/Example Assets/ProjectionPostProcessingProvider.cs
  Assets/LeapMotion/Core/Examples/Example Assets/ProjectionPostProcessingProvider.cs.meta
  Assets/LeapMotion/Core/Examples/Hand Post-Processes (VR).unity
  Assets/LeapMotion/Core/Examples/Hand Post-Processes (VR).unity.meta
  Assets/LeapMotion/Core/Scripts/DataStructures/Pose.cs
  Assets/LeapMotion/Core/Scripts/HandModelManager.cs
  Assets/LeapMotion/Core/Scripts/HandRepresentation.cs
  Assets/LeapMotion/Core/Scripts/LeapProvider.cs
  Assets/LeapMotion/Core/Scripts/Utils/Editor/PostProcessProviderEditor.cs
  Assets/LeapMotion/Core/Scripts/Utils/Editor/PostProcessProviderEditor.cs.meta
  Assets/LeapMotion/Core/Scripts/Utils/HandUtils.cs
  Assets/LeapMotion/Core/Scripts/Utils/PostProcessProvider.cs
  Assets/LeapMotion/Core/Scripts/Utils/PostProcessProvider.cs.meta
  Assets/LeapMotion/Modules/InteractionEngine/Scripts/UI/InteractionButton.cs
Labels: enhancement

#1006 Cleanup LeapC and LeapCSharp
  Assets/LeapMotion/Core/Plugins/LeapCSharp/Arm.cs
  Assets/LeapMotion/Core/Plugins/LeapCSharp/Bone.cs
  Assets/LeapMotion/Core/Plugins/LeapCSharp/CSharpExtensions.cs
  Assets/LeapMotion/Core/Plugins/LeapCSharp/Config.cs
  Assets/LeapMotion/Core/Plugins/LeapCSharp/Connection.cs
  Assets/LeapMotion/Core/Plugins/LeapCSharp/Controller.cs
  Assets/LeapMotion/Core/Plugins/LeapCSharp/Device.cs
  Assets/LeapMotion/Core/Plugins/LeapCSharp/DeviceList.cs
  Assets/LeapMotion/Core/Plugins/LeapCSharp/DistortionData.cs
  Assets/LeapMotion/Core/Plugins/LeapCSharp/Events.cs
  Assets/LeapMotion/Core/Plugins/LeapCSharp/FailedDevice.cs
  Assets/LeapMotion/Core/Plugins/LeapCSharp/FailedDeviceList.cs
  Assets/LeapMotion/Core/Plugins/LeapCSharp/Finger.cs
  Assets/LeapMotion/Core/Plugins/LeapCSharp/Frame.cs
  Assets/LeapMotion/Core/Plugins/LeapCSharp/Hand.cs
  Assets/LeapMotion/Core/Plugins/LeapCSharp/IController.cs
  Assets/LeapMotion/Core/Plugins/LeapCSharp/Image.cs
  Assets/LeapMotion/Core/Plugins/LeapCSharp/LeapC.cs
  Assets/LeapMotion/Core/Plugins/LeapCSharp/LeapQuaternion.cs
  Assets/LeapMotion/Core/Plugins/LeapCSharp/LeapTransform.cs
  Assets/LeapMotion/Core/Plugins/LeapCSharp/Logger.cs
  Assets/LeapMotion/Core/Plugins/LeapCSharp/Matrix.cs
  Assets/LeapMotion/Core/Plugins/LeapCSharp/MessageSeverity.cs
  Assets/LeapMotion/Core/Plugins/LeapCSharp/Vector.cs
Labels: DevX, Documentation, enhancement

#1004 Add more auto-recenter options to XRHeightOffset
  Assets/LeapMotion/Core/Examples/Attachment Hands (VR).unity
  Assets/LeapMotion/Core/Examples/Capsule Hand (VR - Infrared Viewer).unity
  Assets/LeapMotion/Core/Examples/Capsule Hand (VR).unity
  Assets/LeapMotion/Core/Examples/Hand Post-Processes (VR).unity
  Assets/LeapMotion/Core/Examples/Rigged Hands (VR - Infrared Viewer).unity
  Assets/LeapMotion/Core/Examples/Rigged Hands (VR).unity
  Assets/LeapMotion/Core/Plugins/Android.meta
  Assets/LeapMotion/Core/Prefabs/Leap Rig.prefab
  Assets/LeapMotion/Core/Scripts/XR/Editor/XRHeightOffsetEditor.cs
  Assets/LeapMotion/Core/Scripts/XR/XRHeightOffset.cs
  Assets/LeapMotion/Experimental/HierarchyRecording/Examples/Leap Frames/Leap Frames - Recording Setup.unity
  Assets/LeapMotion/Legacy/UIInput/Examples/ExampleUIScene.unity
  Assets/LeapMotion/Legacy/UIInput/Examples/MobileFriendlyUIScene.unity
  Assets/LeapMotion/Modules/Hands/Examples/Scenes/Hands_Viewer_Demo.unity
  Assets/LeapMotion/Modules/Hands/Examples/Scenes/Rigged_Hands_AutoRig_Example.unity
  Assets/LeapMotion/Modules/InteractionEngine/Examples/1. Interaction Objects/Interaction Objects.unity
  Assets/LeapMotion/Modules/InteractionEngine/Examples/2. Basic UI/Basic UI.unity
  Assets/LeapMotion/Modules/InteractionEngine/Examples/3. Interaction Callbacks/Interaction Callbacks.unity
  Assets/LeapMotion/Modules/InteractionEngine/Examples/4. Hand UI/Hand UI.unity
  Assets/LeapMotion/Modules/InteractionEngine/Examples/5. Anchors/Anchors.unity
  Assets/LeapMotion/Modules/InteractionEngine/Examples/6. Dynamic UI/Dynamic UI.unity
  Assets/LeapMotion/Modules/InteractionEngine/Examples/7. Moving Reference Frames/Moving Reference Frames.unity
  Assets/LeapMotion/Modules/InteractionEngine/Examples/8. Swap Grasp/Swap Grasp.unity
Labels: DevX, enhancement

#1009 Pull hierarchy changes from paint
  Assets/LeapMotion/Experimental/HierarchyRecording/Examples/Leap Frames/Leap Frames - Recording Setup.unity
  Assets/LeapMotion/Experimental/HierarchyRecording/Scripts/Editor/HierarchyPostProcessEditor.cs
  Assets/LeapMotion/Experimental/HierarchyRecording/Scripts/HierarchyPostProcess.cs
  Assets/LeapMotion/Experimental/HierarchyRecording/Scripts/HierarchyRecorder.cs
  Assets/LeapMotion/Experimental/HierarchyRecording/Scripts/LeapRecording/VectorHandRecording/VectorHand.cs
  Assets/LeapMotion/Experimental/HierarchyRecording/Scripts/LeapRecording/VectorHandRecording/VectorHandCurves.cs
  Assets/LeapMotion/Experimental/HierarchyRecording/Scripts/MethodRecording/MethodRecording.cs
  Assets/LeapMotion/Experimental/HierarchyRecording/Scripts/RecordedData.cs
  Assets/LeapMotion/Experimental/HierarchyRecording/Scripts/StateMachine/Editor/TransitionBehaviourEditor.cs
  Assets/LeapMotion/Experimental/HierarchyRecording/Scripts/StateMachine/StateBehaviours/SetPlayableDirector.cs
  Assets/LeapMotion/Experimental/HierarchyRecording/Scripts/StateMachine/StateMachine.cs
  Assets/LeapMotion/Experimental/HierarchyRecording/Scripts/StateMachine/Transitions/TransitionAfterPlayable.cs
  Assets/LeapMotion/Experimental/HierarchyRecording/Scripts/StateMachine/Transitions/TransitionOnMarker.cs
  Assets/LeapMotion/Experimental/HierarchyRecording/Scripts/StateMachine/Transitions/TransitionOnMarker.cs.meta
  Assets/LeapMotion/Experimental/HierarchyRecording/Scripts/TimelineMarkers.meta
  Assets/LeapMotion/Experimental/HierarchyRecording/Scripts/TimelineMarkers/DiscontinuityCalculator.cs
  Assets/LeapMotion/Experimental/HierarchyRecording/Scripts/TimelineMarkers/DiscontinuityCalculator.cs.meta
  Assets/LeapMotion/Experimental/HierarchyRecording/Scripts/TimelineMarkers/MarkerClip.cs
  Assets/LeapMotion/Experimental/HierarchyRecording/Scripts/TimelineMarkers/MarkerClip.cs.meta
  Assets/LeapMotion/Experimental/HierarchyRecording/Scripts/TimelineMarkers/MarkerController.cs
  Assets/LeapMotion/Experimental/HierarchyRecording/Scripts/TimelineMarkers/MarkerController.cs.meta
  Assets/LeapMotion/Experimental/HierarchyRecording/Scripts/TimelineMarkers/MarkerTrack.cs
  Assets/LeapMotion/Experimental/HierarchyRecording/Scripts/TimelineMarkers/MarkerTrack.cs.meta
Labels: enhancement

#1011 Old Leap Rig Upgrader
  Assets/LeapMotion/Core/EditorResources/LM_Logo_Black.png
  Assets/LeapMotion/Core/EditorResources/LM_Logo_Black.png.meta
  Assets/LeapMotion/Core/EditorResources/LM_Logo_White.png
  Assets/LeapMotion/Core/EditorResources/LM_Logo_White.png.meta
  Assets/LeapMotion/Core/Scripts/EditorTools.meta
  Assets/LeapMotion/Core/Scripts/EditorTools/Editor.meta
  Assets/LeapMotion/Core/Scripts/EditorTools/Editor/LeapRigUpgrader.cs
  Assets/LeapMotion/Core/Scripts/EditorTools/Editor/LeapRigUpgrader.cs.meta
  Assets/LeapMotion/Core/Scripts/EditorTools/Editor/LeapUnityWindow.cs
  Assets/LeapMotion/Core/Scripts/EditorTools/Editor/LeapUnityWindow.cs.meta
  Assets/LeapMotion/Core/Scripts/EditorTools/LeapPreferences.cs
  Assets/LeapMotion/Core/Scripts/EditorTools/LeapPreferences.cs.meta
  Assets/LeapMotion/Core/Scripts/EditorTools/LeapProjectChecks.cs
  Assets/LeapMotion/Core/Scripts/EditorTools/LeapProjectChecks.cs.meta
  Assets/LeapMotion/Core/Scripts/LeapServiceProvider.cs
  Assets/LeapMotion/Core/Scripts/Utils/Editor/EditorUtils.cs
  Assets/LeapMotion/Core/Scripts/Utils/Editor/EditorUtils.cs.meta
  Assets/LeapMotion/Modules/InteractionEngine/Scripts/Editor/InteractionManagerEditor.cs
  Assets/LeapMotion/Modules/InteractionEngine/Scripts/InteractionManager.cs
  Assets/LeapMotion/Modules/InteractionEngine/Scripts/Internal/Editor.meta
  Assets/LeapMotion/Modules/InteractionEngine/Scripts/Internal/Editor/InteractionChecks.cs
  Assets/LeapMotion/Modules/InteractionEngine/Scripts/Internal/Editor/InteractionChecks.cs.meta
  Assets/LeapMotion/Modules/InteractionEngine/Scripts/Internal/InteractionPreferences.cs
Labels: DevX, enhancement

#1015 Rename post process provider example scripts
  Assets/LeapMotion/Core/Examples/Example Assets/InertiaPostProcessProvider.cs
  Assets/LeapMotion/Core/Examples/Example Assets/InertiaPostProcessProvider.cs.meta
  Assets/LeapMotion/Core/Examples/Example Assets/ProjectionPostProcessProvider.cs
  Assets/LeapMotion/Core/Examples/Example Assets/ProjectionPostProcessProvider.cs.meta
Labels: DevX

#1016 Reorder stop and join attempts when stopping connection
  Assets/LeapMotion/Core/Plugins/LeapCSharp/Connection.cs
Labels: bug

#1018 Update headers and files
  Assets/LeapMotion/Core/Scripts/EditorTools/Editor/LeapRigUpgrader.cs
  Assets/LeapMotion/Core/Scripts/EditorTools/Editor/LeapUnityWindow.cs
  Assets/LeapMotion/Core/Scripts/EditorTools/LeapProjectChecks.cs
  Assets/LeapMotion/Core/Scripts/Utils/Editor/EditorUtils.cs
  Assets/LeapMotion/Experimental/HierarchyRecording/Examples/Events/ColorChanginCubeTimeline.asset
  Assets/LeapMotion/Experimental/HierarchyRecording/Examples/Leap Frames/LeapFramesExampleRecording 01/LeapFramesExampleRecording.asset
  Assets/LeapMotion/Legacy/UIInput/Examples/ExampleUIScene.unity
  Assets/LeapMotion/Legacy/UIInput/Examples/MobileFriendlyUIScene.unity
  Assets/LeapMotion/Modules/InteractionEngine/Scripts/Internal/Editor/InteractionChecks.cs
  Assets/LeapMotion/Modules/InteractionEngine/Testing/EditorResources/Recordings/IE Test Playback Rig - Grasp and Throw.asset
  Assets/LeapMotion/Modules/InteractionEngine/Testing/EditorResources/Recordings/IE Test Playback Rig - Press Button.asset
Labels: Documentation

#1020 Detatch on destroy if we are at runtime
  Assets/LeapMotion/Modules/GraphicRenderer/Scripts/LeapGraphic.cs
Labels: bug
